# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roman/Diplomska/SFM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roman/Diplomska/SFM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Diplomska/SFM/CMakeFiles /home/roman/Diplomska/SFM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Diplomska/SFM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named StructureFromMotion

# Build rule for target.
StructureFromMotion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StructureFromMotion
.PHONY : StructureFromMotion

# fast build rule for target.
StructureFromMotion/fast:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/build
.PHONY : StructureFromMotion/fast

SFM/Image.o: SFM/Image.cpp.o
.PHONY : SFM/Image.o

# target to build an object file
SFM/Image.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/Image.cpp.o
.PHONY : SFM/Image.cpp.o

SFM/Image.i: SFM/Image.cpp.i
.PHONY : SFM/Image.i

# target to preprocess a source file
SFM/Image.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/Image.cpp.i
.PHONY : SFM/Image.cpp.i

SFM/Image.s: SFM/Image.cpp.s
.PHONY : SFM/Image.s

# target to generate assembly for a file
SFM/Image.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/Image.cpp.s
.PHONY : SFM/Image.cpp.s

SFM/MVS.o: SFM/MVS.cpp.o
.PHONY : SFM/MVS.o

# target to build an object file
SFM/MVS.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/MVS.cpp.o
.PHONY : SFM/MVS.cpp.o

SFM/MVS.i: SFM/MVS.cpp.i
.PHONY : SFM/MVS.i

# target to preprocess a source file
SFM/MVS.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/MVS.cpp.i
.PHONY : SFM/MVS.cpp.i

SFM/MVS.s: SFM/MVS.cpp.s
.PHONY : SFM/MVS.s

# target to generate assembly for a file
SFM/MVS.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/MVS.cpp.s
.PHONY : SFM/MVS.cpp.s

SFM/SFM.o: SFM/SFM.cpp.o
.PHONY : SFM/SFM.o

# target to build an object file
SFM/SFM.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/SFM.cpp.o
.PHONY : SFM/SFM.cpp.o

SFM/SFM.i: SFM/SFM.cpp.i
.PHONY : SFM/SFM.i

# target to preprocess a source file
SFM/SFM.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/SFM.cpp.i
.PHONY : SFM/SFM.cpp.i

SFM/SFM.s: SFM/SFM.cpp.s
.PHONY : SFM/SFM.s

# target to generate assembly for a file
SFM/SFM.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/SFM.cpp.s
.PHONY : SFM/SFM.cpp.s

SFM/estimator/LO-RANSAC.o: SFM/estimator/LO-RANSAC.cpp.o
.PHONY : SFM/estimator/LO-RANSAC.o

# target to build an object file
SFM/estimator/LO-RANSAC.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/LO-RANSAC.cpp.o
.PHONY : SFM/estimator/LO-RANSAC.cpp.o

SFM/estimator/LO-RANSAC.i: SFM/estimator/LO-RANSAC.cpp.i
.PHONY : SFM/estimator/LO-RANSAC.i

# target to preprocess a source file
SFM/estimator/LO-RANSAC.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/LO-RANSAC.cpp.i
.PHONY : SFM/estimator/LO-RANSAC.cpp.i

SFM/estimator/LO-RANSAC.s: SFM/estimator/LO-RANSAC.cpp.s
.PHONY : SFM/estimator/LO-RANSAC.s

# target to generate assembly for a file
SFM/estimator/LO-RANSAC.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/LO-RANSAC.cpp.s
.PHONY : SFM/estimator/LO-RANSAC.cpp.s

SFM/estimator/PE-RANSAC.o: SFM/estimator/PE-RANSAC.cpp.o
.PHONY : SFM/estimator/PE-RANSAC.o

# target to build an object file
SFM/estimator/PE-RANSAC.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/PE-RANSAC.cpp.o
.PHONY : SFM/estimator/PE-RANSAC.cpp.o

SFM/estimator/PE-RANSAC.i: SFM/estimator/PE-RANSAC.cpp.i
.PHONY : SFM/estimator/PE-RANSAC.i

# target to preprocess a source file
SFM/estimator/PE-RANSAC.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/PE-RANSAC.cpp.i
.PHONY : SFM/estimator/PE-RANSAC.cpp.i

SFM/estimator/PE-RANSAC.s: SFM/estimator/PE-RANSAC.cpp.s
.PHONY : SFM/estimator/PE-RANSAC.s

# target to generate assembly for a file
SFM/estimator/PE-RANSAC.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/PE-RANSAC.cpp.s
.PHONY : SFM/estimator/PE-RANSAC.cpp.s

SFM/estimator/PROSAC.o: SFM/estimator/PROSAC.cpp.o
.PHONY : SFM/estimator/PROSAC.o

# target to build an object file
SFM/estimator/PROSAC.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/PROSAC.cpp.o
.PHONY : SFM/estimator/PROSAC.cpp.o

SFM/estimator/PROSAC.i: SFM/estimator/PROSAC.cpp.i
.PHONY : SFM/estimator/PROSAC.i

# target to preprocess a source file
SFM/estimator/PROSAC.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/PROSAC.cpp.i
.PHONY : SFM/estimator/PROSAC.cpp.i

SFM/estimator/PROSAC.s: SFM/estimator/PROSAC.cpp.s
.PHONY : SFM/estimator/PROSAC.s

# target to generate assembly for a file
SFM/estimator/PROSAC.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/PROSAC.cpp.s
.PHONY : SFM/estimator/PROSAC.cpp.s

SFM/estimator/RANSAC.o: SFM/estimator/RANSAC.cpp.o
.PHONY : SFM/estimator/RANSAC.o

# target to build an object file
SFM/estimator/RANSAC.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/RANSAC.cpp.o
.PHONY : SFM/estimator/RANSAC.cpp.o

SFM/estimator/RANSAC.i: SFM/estimator/RANSAC.cpp.i
.PHONY : SFM/estimator/RANSAC.i

# target to preprocess a source file
SFM/estimator/RANSAC.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/RANSAC.cpp.i
.PHONY : SFM/estimator/RANSAC.cpp.i

SFM/estimator/RANSAC.s: SFM/estimator/RANSAC.cpp.s
.PHONY : SFM/estimator/RANSAC.s

# target to generate assembly for a file
SFM/estimator/RANSAC.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/RANSAC.cpp.s
.PHONY : SFM/estimator/RANSAC.cpp.s

SFM/estimator/TddTest.o: SFM/estimator/TddTest.cpp.o
.PHONY : SFM/estimator/TddTest.o

# target to build an object file
SFM/estimator/TddTest.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/TddTest.cpp.o
.PHONY : SFM/estimator/TddTest.cpp.o

SFM/estimator/TddTest.i: SFM/estimator/TddTest.cpp.i
.PHONY : SFM/estimator/TddTest.i

# target to preprocess a source file
SFM/estimator/TddTest.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/TddTest.cpp.i
.PHONY : SFM/estimator/TddTest.cpp.i

SFM/estimator/TddTest.s: SFM/estimator/TddTest.cpp.s
.PHONY : SFM/estimator/TddTest.s

# target to generate assembly for a file
SFM/estimator/TddTest.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/TddTest.cpp.s
.PHONY : SFM/estimator/TddTest.cpp.s

SFM/estimator/estimator.o: SFM/estimator/estimator.cpp.o
.PHONY : SFM/estimator/estimator.o

# target to build an object file
SFM/estimator/estimator.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/estimator.cpp.o
.PHONY : SFM/estimator/estimator.cpp.o

SFM/estimator/estimator.i: SFM/estimator/estimator.cpp.i
.PHONY : SFM/estimator/estimator.i

# target to preprocess a source file
SFM/estimator/estimator.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/estimator.cpp.i
.PHONY : SFM/estimator/estimator.cpp.i

SFM/estimator/estimator.s: SFM/estimator/estimator.cpp.s
.PHONY : SFM/estimator/estimator.s

# target to generate assembly for a file
SFM/estimator/estimator.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/SFM/estimator/estimator.cpp.s
.PHONY : SFM/estimator/estimator.cpp.s

tester.o: tester.cpp.o
.PHONY : tester.o

# target to build an object file
tester.cpp.o:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/tester.cpp.o
.PHONY : tester.cpp.o

tester.i: tester.cpp.i
.PHONY : tester.i

# target to preprocess a source file
tester.cpp.i:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/tester.cpp.i
.PHONY : tester.cpp.i

tester.s: tester.cpp.s
.PHONY : tester.s

# target to generate assembly for a file
tester.cpp.s:
	$(MAKE) -f CMakeFiles/StructureFromMotion.dir/build.make CMakeFiles/StructureFromMotion.dir/tester.cpp.s
.PHONY : tester.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... StructureFromMotion"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SFM/Image.o"
	@echo "... SFM/Image.i"
	@echo "... SFM/Image.s"
	@echo "... SFM/MVS.o"
	@echo "... SFM/MVS.i"
	@echo "... SFM/MVS.s"
	@echo "... SFM/SFM.o"
	@echo "... SFM/SFM.i"
	@echo "... SFM/SFM.s"
	@echo "... SFM/estimator/LO-RANSAC.o"
	@echo "... SFM/estimator/LO-RANSAC.i"
	@echo "... SFM/estimator/LO-RANSAC.s"
	@echo "... SFM/estimator/PE-RANSAC.o"
	@echo "... SFM/estimator/PE-RANSAC.i"
	@echo "... SFM/estimator/PE-RANSAC.s"
	@echo "... SFM/estimator/PROSAC.o"
	@echo "... SFM/estimator/PROSAC.i"
	@echo "... SFM/estimator/PROSAC.s"
	@echo "... SFM/estimator/RANSAC.o"
	@echo "... SFM/estimator/RANSAC.i"
	@echo "... SFM/estimator/RANSAC.s"
	@echo "... SFM/estimator/TddTest.o"
	@echo "... SFM/estimator/TddTest.i"
	@echo "... SFM/estimator/TddTest.s"
	@echo "... SFM/estimator/estimator.o"
	@echo "... SFM/estimator/estimator.i"
	@echo "... SFM/estimator/estimator.s"
	@echo "... tester.o"
	@echo "... tester.i"
	@echo "... tester.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

